version: '3'
services:
  app:
    container_name: sequelize.app.postgres
    image: "sequelize.app.postgres"
    build: .
    ports: 
      - "3000:3000"
    restart: always 
    env_file: .env
    depends_on: 
      - sequelizedbpostgres
    volumes:
      - sequelize-app-postgres:/var/lib/sequelize/app/postgres
 

  # Postgres DB
  sequelizedbpostgres:
    container_name: sequelize.db.postgres
    image: "postgres:14.5"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "testdb"
    logging:
      driver: none
    volumes:
      - sequelize-db-postgres:/var/lib/sequelize/db/postgres
      - ./libs/helper/src/db/postgres/testdb.sql:/docker-entrypoint-initdb.d/setup-postgres.sql
      
volumes:
  sequelize-db-postgres:
  sequelize-app-postgres:
