version: '3'
services:
  app:
    container_name: sequelize.app.mysql
    build: .
    ports: 
      - "3000:3000"
    restart: always 
    env_file: .env
    depends_on: 
      - sequelizedbmysql
    volumes:
      - sequelize-app-mysql:/var/lib/sequelize/app/mysql
 
  sequelizedbmysql:
    container_name: sequelize.db.mysql
    image: "mysql:8.0.32"
    restart: always
    ports:
      - "3306:3306"
    command: 
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: "root"
    logging:
      driver: none
    volumes:
      - sequelize-db-mysql:/var/lib/sequelize/db/mysql
      
volumes:
  sequelize-db-mysql:
  sequelize-app-mysql:
