version: '3'
services:
  app:
    container_name: sequelize.app.mssql
    image: "sequelize.app.mssql"
    build: .
    ports: 
      - "3000:3000"
    restart: always 
    env_file: .env
    depends_on: 
      - sequelizedbmssql
    volumes:
      - sequelize-app-mssql:/var/lib/sequelize/app/mssql
 
  sequelizedbmssql:
    container_name: sequelize.db.mssql
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    command: /bin/bash ./entrypoint.sh
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "a1?%fkARF!24x"
      MSSQL_PID: Express
      ACCEPT_EULA: "Y"
    logging:
      driver: none
    volumes:
      - sequelize-db-mssql:/var/lib/sequelize/db/mssql
      - ./libs/core/src/db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./libs/core/src/db/mssql/docker-db-init.sh:/db-init.sh
      - ./libs/core/src/db/mssql/testdb.sql:/db-init.sql
      
volumes:
  sequelize-db-mssql:
  sequelize-app-mssql:
